#!/usr/bin/env bash
# https://jreleaser.org/guide/latest/examples/maven/maven-central.html#_maven

set -TCEeuo pipefail

# Verify release & deploy configuration
echo "Check config"
mvnw --quiet jreleaser:config

# Ensure a clean deployment
echo "Cleaning"
mvnw --quiet clean

# Stage all artifacts to a local directory
echo "Stage Artifacts"
mvnw --quiet -Ppublication

# Deploy and release
echo "Deploy and release"
mvnw jreleaser:deploy
